spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/demodb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: update

server:
  servlet:
    context-path: /api
  error:
    include-message: always

logging:
  level:
    it.laterale.cloud: DEBUG

security:
  secret: nero2005
  prefix: 'Bearer '
  param: Authorization

admin:
  email: fabio.fidone@alice.it
  password: nero2005